// Code generated by coz. DO NOT EDIT.
/**
 * Convert nested object to flatten or expand.
 * @module objnest
 * @version 5.0.0
 */

'use strict'

const create = require('./create')
const Objnest = require('./objnest')

const lib = create()

Object.assign(lib, create, {
  create,
  Objnest
})

module.exports = lib

exports.create = create
exports.expand = lib.expand
exports.flatten = lib.flatten
